//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaZaPracenjePorudzbina
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PorudzbinaEntities1 : DbContext
    {
        public PorudzbinaEntities1()
            : base("name=PorudzbinaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblArtikl> tblArtikls { get; set; }
        public virtual DbSet<tblDobavljac> tblDobavljacs { get; set; }
        public virtual DbSet<tblKupac> tblKupacs { get; set; }
        public virtual DbSet<tblPorudzbina> tblPorudzbinas { get; set; }
        public virtual DbSet<tblStavkaPorudzbine> tblStavkaPorudzbines { get; set; }
    }
}
