//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaZaPracenjePorudzbina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDobavljac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDobavljac()
        {
            this.tblPorudzbinas = new HashSet<tblPorudzbina>();
        }
    
        public int dobavljacID { get; set; }
        public string naziv { get; set; }
        public string adresa { get; set; }
        public string kontakt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPorudzbina> tblPorudzbinas { get; set; }
    }
}
