//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaZaPracenjePorudzbina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPorudzbina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPorudzbina()
        {
            this.tblStavkaPorudzbines = new HashSet<tblStavkaPorudzbine>();
        }
    
        public int porudzbinaID { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<System.DateTime> isporuceno { get; set; }
        public Nullable<decimal> iznos { get; set; }
        public Nullable<bool> placeno { get; set; }
        public Nullable<int> dobavljacID { get; set; }
        public Nullable<int> kupacID { get; set; }
    
        public virtual tblDobavljac tblDobavljac { get; set; }
        public virtual tblKupac tblKupac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStavkaPorudzbine> tblStavkaPorudzbines { get; set; }
    }
}
